Добавлено создание ряда полей и справочников в catebi db в соответствии со структурой датасета cats в Notion
catebi/Catebi.Map pull request #10
Opened 2023-09-29 17:55 UTC by tk0nik

2023-09-29 18:23 UTC, lejafo requested changes

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/catebi_ERD.pgerd
вот этот файлик нужно в отдельной папке держать типа db/schema/docs

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/catebi_db .canvas
и здесь то же самое -> db -> schema -> docs

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +drop table if exists ctb.cat cascade;	-- a dangerous thing
да, каскад стоит убрать совсем конкретно. опасно и непрозрачно

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    cat_id serial PRIMARY KEY,
в такой нотации минус в том, что теряется названием первичного ключа, но можно попробовать оставить, как есть. возможно ничего страшного

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +	cat_sex_id integer NOT NULL,
нет внешнего ключа на поле

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +comment on column ctb.cat.cat_collar_id is 'Ошейник (fk ctb.cat_collar)';
информацию по фк не нужно держать в комментариях

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +comment on column ctb.cat.cat_house_space_id is 'id комнаты в котодоме (fk ctb.cat_house_space)';
то же самое. комментарии это просто краткое описание того или иного поля, но без технических деталей контекста бд

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +comment on column ctb.cat.in_date is 'дата прибытия кошки';
лучше выдерживать в одном стиле: писать с заглавной буквы, либо нет. давай установим, что для комментов всегда будем использовать заглавную начальную

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    cat_id serial PRIMARY KEY,
возможно стоит отметить наименование как сделано для таблицы cat_image_url (59 строка)

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +comment on table ctb.cat_sex is 'словарь: пол';
то же самое про начальную заглавную/строчную

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +comment on column ctb.cat_sex.cat_sex_id is 'id пола (1/2)';
зачем в скобках 1/2?

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    color_id integer,
+ not null

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    color_id integer,
not null

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    name text UNIQUE,
not null

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +	short_name varchar(10),
not null

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    color_id integer,
not null

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +create table ctb.cat2tag (
наверное правильнее все же назвать таблицу cat2cat_tag

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +create table ctb.cat2tag (
плюс не помешает добавить юник на (cat_id, cat_tag_id)

2023-09-29 18:23 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +create table ctb.volunteer (
дополнить not null

2023-09-29 21:02 UTC, lejafo commented
link to #11

2023-09-29 22:34 UTC, tk0nik commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    cat_id serial PRIMARY KEY,
Не совсем поняла 
"теряется названием первичного ключа" - вот эту фразу в частности 
не вижу. чтобы что-то терялось, результат выполнения кажется абсолютно одинаковым
пока оставлю свой вариант, сорян

2023-09-29 22:46 UTC, tk0nik commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +create table ctb.cat2tag (
Протестую, это же таблица как раз для реализации связи "многие ко многим". У одной кошки может быть несколько тегов, и наоборот - котов с тегом "медуход" уже сейчас в ноушене куча. Не буду добавлять

2023-09-30 05:53 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    cat_id serial PRIMARY KEY,
я за единообразие. если мы везде объявляем праймари в контексте задания колонки, то для каждой таблицы так поступаем. у тебя в таблицах-справочниках с этим ок, а вот для таблицы с линками на картинки оно в другом стиле сделано. поправишь для `cat_image_url`, чтобы оно было как и для всех остальных?

2023-09-30 05:56 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +create table ctb.cat2tag (
погоди, у нас ничего не ломается в контексте многие ко многим, просто мы исключаем таким образом дубли по ключу кошка-ошейник (в смысле, что не может быть такого, что одна и та же кошка будет одновременно в двух одинаковых ошейниках)

2023-09-30 08:02 UTC, tk0nik commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +	cat_sex_id integer NOT NULL,
исправлено (строка 181)

2023-09-30 11:24 UTC, lejafo approved these changes
super !

2023-09-30 11:24 UTC, lejafo commented on db/changelog/releases/1.0.0/02._cat_tables.sql
> +    cat_image_url_id serial PRINARY KEY,
ошибка primary с ошибкой

2023-09-30 11:24 UTC, merged